export {
  Wallet,
  Wallet as WalletIcon,
  TrendUp,
  TrendUp as TrendUpIcon,
  CreditCard,
  CreditCard as CreditCardIcon,
  ChatCircle,
  ChatCircle as ChatCircleIcon,
  Sparkle,
  Sparkle as SparkleIcon,
  ShieldCheck,
  ShieldCheck as ShieldCheckIcon,
  CheckCircle,
  CheckCircle as CheckCircleIcon,
  WarningCircle,
  WarningCircle as WarningCircleIcon,
  ClockCountdown,
  ClockCountdown as ClockCountdownIcon,
  XCircle,
  XCircle as XCircleIcon,
  ArrowUpRight,
  ArrowUpRight as ArrowUpRightIcon,
  ArrowDownLeft,
  ArrowDownLeft as ArrowDownLeftIcon,
  Calendar,
  Calendar as CalendarIcon,
  Receipt,
  Receipt as ReceiptIcon,
  Sliders,
  Sliders as SlidersIcon,
  Lock,
  Lock as LockIcon,
  Flame,
  Flame as FireIcon,
  PaperPlaneRight,
  PaperPlaneRight as PaperPlaneRightIcon,
  Scissors,
  Scissors as ScissorsIcon,
  Info,
  Info as InfoIcon,
  type IconProps,
  type IconWeight,
} from "phosphor-react-native";
